plugins:
  - serverless-esbuild
  - ./plugins/stacks_outputs.js

custom:
  secrets: ${file(./config/${opt:stage, 'dev'}.json)}

service: ${self:custom.secrets.service.name}

frameworkVersion: "3"

provider:
  name: ${self:custom.secrets.provider.name}
  runtime: ${self:custom.secrets.provider.runtime}
  stage: ${self:custom.secrets.provider.stage, 'dev'}
  region: ${self:custom.secrets.provider.region}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    BOT_NAME: ${self:custom.secrets.provider.environment.BOT_NAME}-${self:provider.stage}
    BOT_DOMAIN: ${self:custom.secrets.provider.environment.BOT_DOMAIN}
    TELEGRAM_BOT_TOKEN: ${self:custom.secrets.provider.environment.TELEGRAM_BOT_TOKEN}
    DYNAMODB_TABLE_USERS: ${self:provider.environment.BOT_NAME}-${self:custom.secrets.provider.environment.DYNAMODB_TABLE_USERS}
    DYNAMODB_TABLE_GROUPS: ${self:provider.environment.BOT_NAME}-${self:custom.secrets.provider.environment.DYNAMODB_TABLE_GROUPS}
    DYNAMODB_TABLE_COMMANDS: ${self:provider.environment.BOT_NAME}-${self:custom.secrets.provider.environment.DYNAMODB_TABLE_COMMANDS}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

resources:
  - ${file(./src/resources/dynamodb-users-table.yml)}
  - ${file(./src/resources/dynamodb-groups-table.yml)}
  - ${file(./src/resources/dynamodb-commands-table.yml)}
  - ${file(./src/resources/outputs.yml)}

functions:
  authorizer: ${file(./src/functions/authorizer/function.yml)}
  telegramSetWebhook: ${file(./src/functions/telegram_set_webhook/function.yml)}
  telegramWebhook: ${file(./src/functions/telegram_webhook/function.yml)}
  dynamoDBUsersCrud: ${file(./src/functions/dynamo_users_crud/function.yml)}
  dynamoDBCommandsCrud: ${file(./src/functions/dynamo_commands_crud/function.yml)}
  botnorreaCreateApiKey: ${file(./src/functions/botnorrea_create_api_key/function.yml)}
  botnorreaCommandsCreate: ${file(./src/functions/botnorrea_commands_create/function.yml)}
  botnorreaCommandsList: ${file(./src/functions/botnorrea_commands_list/function.yml)}
  botnorreaCommandsRemove: ${file(./src/functions/botnorrea_commands_remove/function.yml)}
